
- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  become: true
  npm:
    name: pm2
    global: yes 
        